/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#10b981',
        'primary-container': '#059669',
        'on-primary': '#ffffff',
        secondary: '#0ea5e9',
        'secondary-container': '#0284c7',
        tertiary: '#f59e0b',
        'vue-teal': '#42b883',
        surface: '#ffffff',
        'surface-variant': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-low': '#e2e8f0',
        'surface-container-lowest': '#f8fafc',
        'surface-container-high': '#cbd5e1',
        'surface-canvas': '#ffffff',
        'inverse-surface': '#0f172a',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'surface-subtle': '#94a3b8',
        'code-dark': '#020617',
        'emerald-glow': '#34d399',
        'primary-fixed': '#a7f3d0',
        'secondary-fixed': '#bae6fd',
        'primary-fixed-dim': '#6ee7b7',
        'tertiary-fixed-dim': '#fcd34d',
        'error': '#ef4444',
      },
      spacing: {
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '3rem',
        'margin': '1.5rem',
      },
      fontFamily: {
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'body-sm': ['"Inter"', 'sans-serif'],
        'label-code': ['"JetBrains Mono"', 'monospace'],
        'label-badge': ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['3.5rem', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-code': ['0.875rem', { lineHeight: '1.5', fontWeight: '500' }],
        'label-badge': ['0.75rem', { lineHeight: '1.5', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
}
