/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb2bb",
        "surface-subtle": "#F1F5F9",
        "surface-container-high": "#e2e7ff",
        "primary-fixed-dim": "#4edea3",
        "surface-container": "#eaedff",
        "tertiary": "#b32349",
        "on-primary-fixed-variant": "#005236",
        "background": "#faf8ff",
        "surface-tint": "#006c49",
        "secondary-fixed": "#89f5e7",
        "border-subtle": "#E2E8F0",
        "on-secondary": "#ffffff",
        "primary-container": "#10b981",
        "tertiary-fixed": "#ffd9dd",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#770028",
        "secondary-container": "#86f2e4",
        "surface-canvas": "#F8FAFC",
        "on-surface-variant": "#3c4a42",
        "surface": "#faf8ff",
        "on-secondary-container": "#006f66",
        "primary": "#006c49",
        "vue-teal": "#42B883",
        "on-primary-container": "#00422b",
        "inverse-on-surface": "#eef0ff",
        "emerald-glow": "#34D399",
        "error": "#ba1a1a",
        "outline-variant": "#bbcabf",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-secondary-fixed": "#00201d",
        "surface-container-low": "#f2f3ff",
        "secondary": "#006a61",
        "on-surface": "#131b2e",
        "on-primary-fixed": "#002113",
        "error-container": "#ffdad6",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "code-dark": "#0B1120",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed-variant": "#005049",
        "on-tertiary-fixed": "#400012",
        "on-tertiary-fixed-variant": "#910033",
        "inverse-primary": "#4edea3",
        "outline": "#6c7a71",
        "surface-container-highest": "#dae2fd",
        "tertiary-container": "#ff778e",
        "inverse-surface": "#283044",
        "primary-fixed": "#6ffbbe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "margin": "2rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1.25rem"
      },
      fontFamily: {
        "label-code": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-badge": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-code": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
